runtime: php73

handlers:
- url: .css
  static_dir: css
  secure: always
  redirect_http_response_code: 301
  
- url: /img/(.+\.(gif|png|jpg))$
  static_files: img/\1
  upload: img/.*\.(gif|png|jpg)$
  
- url: /.*
  script: index.php
